### PR TITLE
ember-get-config 1.0.0

### PR DESCRIPTION
**Pull request by davideferre**
Upgrades ember-get-config to 1.0.0 with embroider support and re-enables embroider optimized scenario for ember try

### CODE REVIEW

**Comment by jrjohnson** [comment]
Thanks @davideferre for getting this (and everything else) added!

**Comment by davideferre** [comment]
> Thanks @davideferre for getting this (and everything else) added!
Thanks to @NullVoxPopuli and you @jrjohnson for your previous PR inspiring this code!

Do you know if there is a release date for a package with this fix?

**Comment by jrjohnson** [comment]
I requested a release from the Fortawesome team and I'd expect `0.3.0` at some point today or tomorrow.

**Comment by robmadole** [comment]
`0.3.0` is published now!

**Pull request merged**
