### PR TITLE
update ember-get-config

### PR DESCRIPTION
**Pull request by mansona**
I recently hit the same error that we see in https://github.com/FortAwesome/ember-fontawesome/issues/205 where you get the dreaded: 

```
[Embroider:MacrosConfig] the given config from '/Users/me/Projects/ember-foo/node_modules/ember-get-config' for packageName 'undefined' is not JSON serializable.
```

when you try to build app. This makes total sense considering what EmbrioiderMacros does but I recently released a version of `ember-get-config` (I'm the maintainer 😂) that fixes this problem because it doesn't serialize the config anymore 👍 

This PR upgrades `ember-get-config` to that new version 🎉

### CODE REVIEW

**Comment by mkszepp** [comment]
@jrjohnson this change was braking in 0.3.3, when a other package is using 1.0.0 the update is not possible. Maybe it shoud be reverted in 0.3.x and readded in 0.4.x

The other possiblity would be to add in dependency: `"ember-get-config": "^1.0.1 || ^2.0.0",` so there is not beaking

**Comment by robmadole** [comment]
I'm chatted with @jrjohnson on this and I'll be releasing 0.4.0 and deprecating 0.3.3 here in just a bit.

**Comment by robmadole** [comment]
Ok. 0.3.3 is deprecated and a 0.4.0 and 0.3.4 (without ember-get-config@2.x dependency) are released.

Let me know if this is still causing pain!

**Comment by mkszepp** [comment]
@robmadole thank for the revert, confirm that there is now possibile the update to 0.3.4

**Pull request merged**
