### PR TITLE
Update to Ember CLI 3.0.0

### PR DESCRIPTION
**Pull request by jrjohnson**
Just keeping everything up to date and fixing some ESLint issues.

### CODE REVIEW

**Comment by mlwilkerson** [comment]
Oh, and `ember test` also fails ESLint for the same reason.

**Comment by jrjohnson** [comment]
Oh sorry, I missed that one.  I will fix and re-submit tonight.

**Comment by mlwilkerson** [comment]
No worries. Thanks for the PR!

**Comment by jrjohnson** [comment]
So there isn't actually a well supported way to handle the case in 
`if('_frameworkStyle' in this.attrs) throw new Error`.  I'm not completely up to date on the specifics, but I think `this.attrs` can sometimes contain unexpected data depending on the way it was invoked.  

There appear to be some complicated ways to do this, but I think the `_` convention is probably going to be effective agains accidentally setting this.

**Comment by mlwilkerson** [comment]
OK, but in this case, the reason for the extra paranoia on my part is because it's a security sensitive issue. What's set in `_frameworkStyle` ends up being returned as `htmlSafe` in the `safeStyle` computed property. So that `throw` is to make sure someone doesn't bind user input to that thing. Ember has a nice warning when you try to bind to the `style` attribute, but we're basically circumventing that here—to allow for the fontawesome API to bubble up some style settings that _should_ be bindable to the `svg`'s style. So, I'm trying to open up that style binding from one direction but not the other.

The reason I used `this.attrs` is because it seemed to be a way to test just what I was looking for: whether `_frameworkStyle` was provided by the template, without getting confused by this one being set internally:
`this.set('_frameworkStyle', abstract.attributes[attr])`

So either: (a) is there another way to do this that is safe? or, (b) maybe you could convince me that this is safe enough without the check?

**Comment by joelkallman** [comment]
@mlwilkerson I agree that Option B is a bad idea. You can accomplish Option A by verifying the string is safe and then only throw the error if it is not safe. It still may be a problem that a developer would attempt to override the property, but at least it's not a security problem.

```js
import { isHTMLSafe } from '@ember/string'

if (!isHTMLSafe(this.get('_frameworkStyle'))) {
   throw new Error('_frameworkStyle attribute is reserved for internal use and may not be set from a template')
}
```

**Comment by mlwilkerson** [comment]
@joelkallman that's a thought-provoking idea, thanks. Reasoning it through, though, wouldn't
```javascript
!isHTMLSafe(this.get('_frameworkStyle'))
```
_always_ be true? We never actually set `_frameworkStyle` to a safe string; we just use it to compute and return the `htmlSafe`d `safeStyle` computed property.

**Comment by jrjohnson** [comment]
I've gone ahead and just disabled this linting rule for now and created #15 to document this issue so it didn't get wrapped up in this otherwise routine update.

**Pull request merged**
