### PR TITLE
Angle bracket examples

### PR DESCRIPTION
**Pull request by maxwondercorn**
- Added angle bracket examples to the readme
- Changed single quotes in examples to double quotes.  Ember convention is double quotes in templates - single quotes are flagged during linting
- CONTRIBUTING.MD - Changed Angular references to Ember

### CODE REVIEW

**Comment by jrjohnson** [comment]
Thanks for this @maxwondercorn! I think we can make the docs even better by dropping clasic `{{fa-icon}}` invocation entirely as Ember v3.4 is the oldest supported version and it supports this syntax. What do you think?

If this seems like a good idea can you update all the test invocations to the new angle-bracket syntax as well?

**Comment by maxwondercorn** [comment]
I think that is a great idea. I’ll work on it in a couple days including tests

**Comment by maxwondercorn** [comment]
This PR is ready for review.  I started the updates to CHANGELOG.md for the next version bump

**Comment by maxwondercorn** [comment]
I didn't realize the addon was still testing against 2.18 which is the test failures.  I can revert the test back to classic invocations or the PR can sit until the addon is upgraded to Ember 3.8.  If you're following recommendations, only the last two LTS versions are tested.

If we want to wait then I can rebase against master after the upgrade.  Either one is fine with me, just let me know what you would like me to do.

**Comment by jrjohnson** [comment]
@maxwondercorn it looks like the addon blueprint for ember-cli 3.11 (which should get released any day now) does drop support for 2.18. I'll keep an eye on it and update and then you can update.

I started #110 to get ahead of updates a bit.

**Comment by jrjohnson** [comment]
@maxwondercorn #111 unlocks this, can you rebase and tests should pass? Also you should remove your edits to the changelog as those will be generated with the release notes.

**Comment by maxwondercorn** [comment]
@jrjohnson rebase completed

**Pull request merged**
