### PR TITLE
Update automatic-replacement-section

### PR DESCRIPTION
**Pull request by basz**

### CODE REVIEW

**Comment by jrjohnson** [comment]
This looks good to me (and is what I'm using in production), just would like @mlwilkerson or @robmadole  to check it out to ensure we're using this API correctly and that calling it a bunch of times in a bunch of components with each call scoped to that components element is a good idea.

**Comment by jrjohnson** [comment]
Oh yea. I'm looking back and ours now looks like this to improve it when the element doesn't exist. Probably worth adding something about this to your docs @basz.

```
didRender() {
  next(() => {
    if (this.element) {
      dom.i2svg({node: this.element});
    }
  });
},
```

**Comment by basz** [comment]
voila

**Comment by jrjohnson** [comment]
Just going to go ahead and merge, even if we have to change them later these seem like valuable instructions to get out there.

**Pull request merged**
