### PR TITLE
Update support matrix

### PR DESCRIPTION
**Pull request by NullVoxPopuli**

### CODE REVIEW

**Comment by jrjohnson** [comment]
My only objection is depending on the unstable `getGlobalConfig` from @embroider/macros without any guarantees around this API or its compatibility with older builds. It's super difficult to actually test application configuration in the dummy app, so we'll need to validate this change continuously with any version bump of embroider. I'm hesitant to take on that maintenance burden and I'm wondering if https://github.com/embroider-build/embroider/pull/770 means we can keep our existing usage of `ember-get-config`?

**Comment by NullVoxPopuli** [comment]
Unless https://github.com/embroider-build/embroider/pull/770 isn't released, that PR wasn't enough to _not_ need the changes in this PR (#174): https://github.com/NullVoxPopuli/limber/pull/114

> without any guarantees around this API or its compatibility with older build

is ember-try not sufficient? 🤔

**Comment by jrjohnson** [comment]
> is ember-try not sufficient
I wish! But testing an add-on against multiple different application configurations isn't doable without jumping through hoops. 

I believe the compatibility fixes are in 0.41.0 so it is released, sad it isn't working. I'll find some time to poke around in `getGlobalConfig` and see how complicated it is (and how likely it is to be a problem for us down the road).

**Comment by NullVoxPopuli** [comment]
what's the verdict?

**Comment by jrjohnson** [comment]
Waiting on https://github.com/mansona/ember-get-config/pull/29 As far as I can tell something needs to be fixed in embroiderer.

**Comment by davideferre** [comment]
> Waiting on [mansona/ember-get-config#29](https://github.com/mansona/ember-get-config/pull/29) As far as I can tell something needs to be fixed in embroiderer.

@jrjohnson  ember-get-config is been updated to 1.0.0 version with Embroider support!

**Comment by jrjohnson** [comment]
Thanks @davideferre, if you feel like opening a PR with that update I'd be happy to merge it.

**Comment by davideferre** [comment]
> Thanks @davideferre, if you feel like opening a PR with that update I'd be happy to merge it.

Thanks @jrjohnson I've created PR #192

**Comment by jrjohnson** [comment]
Thanks for getting this so far @NullVoxPopuli and for the advocacy upstream to get everything in shape. Closing in favor of #192

**Pull request closed without merging**
